### ISSUE TITLE
Null Reference Exception in IsDefinedInAncestor

### ISSUE THREAD

**Issue by Hosch250** [Vannevelj/VSDiagnostics#354] opened 2016-01-10 20:11 UTC
See https://github.com/Vannevelj/VSDiagnostics/blob/develop/VSDiagnostics/VSDiagnostics/VSDiagnostics/Utilities/Extensions.cs#L163

In https://github.com/ServiceStack/ServiceStack.Redis

**Comment by Vannevelj** [comment] 2016-01-10 20:13
Duplicate of https://github.com/Vannevelj/VSDiagnostics/issues/288

**Closed by Vannevelj** 2016-01-10 20:13 UTC
Labels: bug
