### ISSUE TITLE
Implement Settings/Preferences

### ISSUE THREAD

**Issue by somebody1234** [Vannevelj/VSDiagnostics#53] opened 2015-05-27 08:47 UTC
Let users change default settings (e.g. naming conventions, brace conventions)

**Comment by Vannevelj** [comment] 2015-05-27 10:35
This is definitely something I'm interested in but I'm not entirely sure if it's actually possible to do so. Do you have something in mind?

**Comment by somebody1234** [comment] 2015-05-28 08:42
Apparently, you do it like [this](http://haacked.com/archive/2014/07/30/visual-studios-extensions-settings/).

**Comment by Vannevelj** [comment] 2015-05-28 20:17
The problem is that currently, VSDiagnostics is only released as a NuGet package and not an extension. I will keep it in mind to research at a later point in time though if someone knows a way, I'm always interested.

For completeness' sake: if someone wants to turn off a feature temporarily or permanently this can be done through the Supress Warnings dialog that pops up. Although I'm not sure if this is for both CodeFixes and Analyzers or just the former.

**Comment by Hosch250** [comment] 2017-01-08 05:19
Beyond brace/naming conventions, we could allow:

1) Custom generated file extensions
2) Custom comment regex/string literal matches for us to fire an "Info" diagnostic on.

**Comment by JohanLarsson** [comment] 2017-01-08 11:52
[StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) uses a settings file.

**Closed** 2023-04-03 18:47 UTC
Labels: type - feature, priority - medium
